export {
  WORLD_BLOCK_BYTES,
  WORLD_MESHES_PER_BLOCK,
  WORLD_MESH_GRID,
  WORLD_MESH_EXTENT,
  WORLD_BLOCK_EXTENT,
  WORLD_GRIDS,
  WM0_ALTERNATIVE_CELLS,
  WM0_ALTERNATIVE_GROUPS,
  resolveBlockIndex,
  TEXTURE_ID_MASK,
  LOCATION_ID_SHIFT,
  LOCATION_ID_MASK,
  TEXTURE_FLAG_BIT,
  decodeTextureWord,
  type TextureWordParts,
  type WorldGrid,
  type WorldTriangle,
  type WorldMesh,
  type WorldBlock,
  type WorldTerrain,
  type WorldDiagnostic,
  type WorldDiagnosticCode,
} from './types.js';
export { parseWorldMesh, parseWorldBlock, parseWorldMap, type ParseBlockResult } from './parse.js';
export {
  parseWorldTextureNames,
  WORLD_UNDERWATER_TEXTURES,
  WORLD_GLACIER_TEXTURES,
  type WorldTextureNameTable,
} from './texture-names.js';
export {
  parseWorldAnimatedTextures,
  WORLD_ANIM_BITS_PER_PIXEL,
  type WorldAnimatedSet,
  type WorldAnimatedTexture,
  type WorldAnimatedFrame,
} from './wm-ta.js';
export {
  parseFieldTbl,
  fieldTblEntry,
  fieldTblEntryForOpcode,
  fieldTblEntryWithFallback,
  FIELD_TBL_RECORD_COUNT,
  FIELD_TBL_ENTRY_BYTES,
  FIELD_TBL_RECORD_BYTES,
  FIELD_TBL_BYTES,
  type FieldTable,
  type FieldTblRecord,
  type FieldEntryPoint,
  type FieldTblScenario,
  type FieldTblDiagnostic,
  type FieldTblDiagnosticCode,
} from './field-tbl.js';
export {
  parseWorldEv,
  EV_FILE_BYTES,
  EV_CODE_BASE_WORDS,
  EV_TABLE_SENTINEL,
  WOP_RETURN,
  WOP_RESET,
  WOP_GOTO,
  WOP_GOTO_IF_FALSE,
  WOP_OPERAND1,
  WOP_CALL_BASE,
  WOP_CALL_LAST,
  WOP_WAIT_SET,
  WOP_WAIT,
  WOP_SET_WORLD_PROGRESS,
  WOP_ENTER_FIELD,
  WORLD_PROGRESS_MAX,
  WORLD_CMD_POPS,
  WORLD_CMD_PUSHES,
  type WorldEv,
  type EvFunction,
  type EvFunctionType,
  type EvDiagnostic,
} from './ev.js';
